### ISSUE TITLE
Extension from TER is missing LightSAML

### ISSUE THREAD

**Issue by neufeind** [DMKEBUSINESSGMBH/mksamlauth#32]
The extension works fine when used in a composer-context and pulling its dependencies. But there is also the extension installable from TER. And that does not ship with LightSAML and there is no separate LightSAML-extension available or so providing the needed classes.

As a workaround it works if you manually pull LightSAML and dependencies (for example via composer) and autoload the classes before using mksamlauth. So it looks like the TER-extension (or together with a companion-extension providing lightsaml?) could be changed to work also non-composer-based.

**Comment by Slydder** [comment]
We are currently trying to get this working as well. We have lightsaml, symfony http-founder and paragonie in vendors. afterwards we get a white screen after installing mksamlauth. how did you get it working?

It currently dies because it can't find Enricher. So I imagine that the Class mappings are incorrect.

**Comment by Slydder** [comment]
OK. we did a composer install on a dev system and migrated the changes over to our test system and now mksamlauth is installed and no white screen. Mostly changes in vendor/composer/autoload_namespaces.php and vendor/composer/autoload_static.php were needed for LightSaml to be found.

This lead to mksamlauth being installed but without a menu item. In "Admin Tools" -> "Settings" -> "Extension Configuration" there is no listing for mksamlauth though. soooooo.

We can also disable and enable mksamlauth but it has no visible effect. There are also no errors thrown in the logs.

**Comment by RocKordier** [comment]
Hey @Slydder ,
IMHO you should never modify files and folders in `vendor` directory on installations by your own.
Also "transfering" all the source files from one to another server should caused very carefully. Its better to package and deploy via continuous delivery Pipleines.

mksamlauth doesn't have any BEModule. Configuration could be done with some records. Have a quick look into the [Administration Guide](https://github.com/DMKEBUSINESSGMBH/mksamlauth/tree/8.7/Documentation/Administration%20Guide).

Eric

**Comment by Slydder** [comment]
@RocKordier ,

Well in a normal situation I would not. However, there are 3 SAML Auth packages total. 1 does not and will not even be considered. 2 will not install.

Of the 2 that will not install. mksamlauth is the only one that seems to be coded to be compatible with 9.5.11. So it's either recode deprecated calls/functions in the other one or get the needed libraries installed in our normal system for mksamlauth.

I, personally hate having to do any of this. However, the state of SAML support in typo3 is forcing our hand here.

**Comment by RocKordier** [comment]
Thats correct.We offer 9.5 support, but we dont have a schedule to upgrade to T3 10 LTS ATM.

I'll close the issue.
Feel free to open an new issue if you have another problem.
