### ISSUE TITLE
Extension causes white screen

### ISSUE THREAD

**Issue by Slydder** [DMKEBUSINESSGMBH/mksamlauth#34]
Hey all,

We are running 9.5.11 and tried installing the extension through the extension manager which causes a white screen directly afterwards. I have looked and found it is trying to load lightsaml and is unable to find the files.

**Comment by RocKordier** [comment]
Hey @Slydder ,
the extension does not offer support for an installation without composer because we dont ship any related library. I might think we  announced that in some support documents. 😬

**Comment by Slydder** [comment]
not good if none of the installs are composer installs.

**Comment by Baachi** [comment]
Hey @Slydder ,

thanks for you interest! As @RocKordier already said, we don't support TER release yet. It's only listed for marketing reasons.

In the PHP ecosystem is composer the standard way to install libraries. It brings you some really nice features and performance improvements, so give it a try. :)

Currently, I expirement myself with automatic TER releases through GitHub Actions, so there is a chance we might support it in a while, but there is no guarantee for that.
